# -*- coding: utf-8 -*-
"""tarea2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KZnhVAy-Pv70Cqbbm8rjseKfwW5Ixc2

# EJERCICIO 1, 2 Y 3
"""

def codigo1():

    naci = int(input("ingresa tu año de nacimiento: "))
    edad = 2024 - naci
    mensaje = []

    def ejercicio1():
        if edad >= 18:
          vali = f"felicidades, tienes {edad} años, eres mayor de edad y "
        else:
          falta = 18 - edad
          vali = f"tienes {edad} años y te faltan {falta} años para ser mayor de edad y "
        return vali

    def ejercicio2():
        if naci >= 2013:
          gen = "eres generacion Alfa"
        elif naci >= 1997:
          gen = "eres generacion Z"
        elif naci >= 1981:
          gen = "eres millennial"
        elif naci >= 1965:
          gen = "eres generacion X"
        elif naci >= 1946:
          gen = "eres baby Boomer"
        else:
          gen = "eres generacion silent"
        return gen

    def ejercicio3():
        if edad % 10 == 0:
          div = ", ademas tu edad es un número redondo. "
        else:
          div = ""
        return div

    mensaje.extend([ejercicio1(), ejercicio2(), ejercicio3()])


    print(*mensaje)


codigo1()

"""# EJERCICIO 4"""

def contactos():
    conta = {}

    def errorblanco(msg):
        while True:
            vali = input(msg)
            if vali != "":
                return vali
            else:
                print("\n!!!!Error: dato en blanco!!!!\n")

    def errorvacio():
        if not conta:
            print("No existen contactos, porfavor crear uno")
            return True
        return False

    def agregar():
        print("\n---------------\n")
        nom = errorblanco("Digite el nombre del contacto: ")
        cel = errorblanco("Digite el teléfono del contacto: ")
        conta[nom] = cel
        print("Contacto agregado.")

    def buscar():
        print("\n---------------\n")
        if errorvacio():
            return
        nom = errorblanco("Digite el nombre del contacto: ")
        if nom in conta:
            print(f"El telefono de {nom} es {conta[nom]}")
        else:
            print("Contacto no encontrado.")

    def mostrar():
        print("\n---------------\n")
        if errorvacio():
            return
        print("Lista de contactos:")
        for nom, cel in conta.items():
            print(f"{nom}: {cel}")

    def editar():
        print("\n---------------\n")
        if errorvacio():
            return
        nom = errorblanco("Digite el nombre del contacto: ")
        if nom in conta:
            cel = errorblanco("Digite el nuevo telefono: ")
            conta[nom] = cel
            print("Teléfono actualizado.")
        else:
            print("\n**Contacto no encontrado**")

    def menu():
        while True:
            print("\n---------------\n")
            print("1. Agregar")
            print("2. Buscar")
            print("3. Mostrar")
            print("4. Editar")
            print("5. Salir")

            opcion = errorblanco("Seleccione una opcion: ")

            if opcion == '1':
                agregar()
            elif opcion == '2':
                buscar()
            elif opcion == '3':
                mostrar()
            elif opcion == '4':
                editar()
            elif opcion == '5':
                print("Finalizado.")
                break
            else:
                print("Opcion incorrecta.")

    menu()
contactos()

"""# EJERCICIO 5"""

def invitados():
    conta = []

    def errorblanco(msg):
        while True:
            vali = input(msg)
            if vali != "":
                return vali
            else:
                print("\n!!!!Error: dato en blanco!!!!\n")

    def errorvacio():
        if not conta:
            print("**No existen invitados, porfavor crear uno**")
            return True
        return False

    def agregar():
        print("\n---------------\n")
        nom = errorblanco("Digite el nombre del invitado: ")
        conta.append(nom)
        print("invitado agregado.")

    def buscar():
        print("\n---------------\n")
        if errorvacio():
            return
        nom = errorblanco("Digite el nombre del invitado buscado: ")
        if nom in conta:
            print(f"{nom} esta en la lista de invitados")
        else:
            print("\n**invitado no encontrado**")

    def eliminar():
        print("\n---------------\n")
        if errorvacio():
            return
        nom = errorblanco("Digite el nombre del invitado a eliminar: ")
        if nom in conta:
            conta.remove(nom)
            print("invitado eliminado.")
        else:
            print("\n**invitado no encontrado**")

    def editar():
        print("\n---------------\n")
        if errorvacio():
            return
        nom = errorblanco("Digite el nombre del invitado: ")
        if nom in conta:
            nunom = errorblanco("Digite el nuevo invitado: ")
            index = conta.index(nom)
            conta[index] = nunom
            print("invitado actualizado.")
        else:
            print("\n**invitado no encontrado**")

    def menu():
        while True:
            print("\n---------------\n")
            print("1. Agregar")
            print("2. Buscar")
            print("3. eliminar")
            print("4. Editar")
            print("5. Salir")

            opcion = errorblanco("Seleccione una opcion: ")

            if opcion == '1':
                agregar()
            elif opcion == '2':
                buscar()
            elif opcion == '3':
                eliminar()
            elif opcion == '4':
                editar()
            elif opcion == '5':
                print("Finalizado.")
                break
            else:
                print("Opcion incorrecta.")

    menu()
invitados()